### ISSUE TITLE
每条书签的右键菜单可以适当扩展一下，拖拽功能也是有需求的

### ISSUE THREAD

**Issue by tianc43** [qinxs/Ease-Bookmarks#1]

**Comment by qinxs** [comment]
你好

书签右键菜单适当扩展一下，这个具体是指什么？

拖拽功能，目前支持以下两种情况：
1. 当前文件夹下书签排序
2. 将当前文件件下的书签移动到当前目录的子文件夹中
如果跨文件夹移动这种（类似的还有批量操作），建议使用浏览器自带的书签管理器操作（比如Chrome：用快捷键`Ctrl + Shift + O` 打开）
因为本扩展的书签不是以树形结构显示全部书签的，所以实现跨文件夹移动比较难

**Comment by tianc43** [comment]
您好，非常感谢您的回信。
我刚才调整了自己的edge布局，需要一个收藏夹插件，所以才看到了您的作品。
我只是简单地试用了一下，比较称心如意，就拿来直接用了。
刚才发现不能进行跨文件夹拖拽，遂留言了，您的回复解决了我的疑虑。
右键菜单扩展可能也不需要了，是我没有看仔细。
最后，再次感谢您的回信，我会持续关注的，加油！
非常有兴趣加入您的项目，只是目前时间不太允许，希望以后有机会。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinxs/Ease-Bookmarks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qinxs/Ease-Bookmarks] 每条书签的右键菜单可以适当扩展一下，拖拽功能也是有需求的 (Issue #1)





 
你好
 
书签右键菜单适当扩展一下，这个具体是指什么？
 
拖拽功能，目前支持以下两种情况：
  
当前文件夹下书签排序
 
将当前文件件下的书签移动到当前目录的子文件夹中
 如果跨文件夹移动这种（类似的还有批量操作），建议使用浏览器自带的书签管理器操作（比如Chrome：用快捷键Ctrl + Shift + O 打开）
 因为本扩展的书签不是以树形结构显示全部书签的，所以实现跨文件夹移动比较难
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qinxs** [comment]
好的~
那我关闭这条issue了
