### ISSUE TITLE
Potential bug: The popup does not close after clicking when a bookmark is set to open in the current tab

### ISSUE THREAD

**Issue by hellodrsoul** [qinxs/Ease-Bookmarks#11]
If you set to open a bookmark in ''Current tab'' inside the options for the extension, the popup of the extension won't automatically close after clicking the bookmark. You need to click again outside the popup to close the popup. 
When the extension is set to open a bookmark in ''New tab'', the popup will close automatically once the bookmark is clicked. This is normal behavior and the same should be observed when you set the extension to open the bookmark in current tab.
Cheers

**Comment by qinxs** [comment]
> If you set to open a bookmark in ''Current tab'' inside the options for the extension, the popup of the extension won't automatically close after clicking the bookmark. You need to click again outside the popup to close the popup. When the extension is set to open a bookmark in ''New tab'', the popup will close automatically once the bookmark is clicked. This is normal behavior and the same should be observed when you set the extension to open the bookmark in current tab. Cheers

Fixed!
Please update to the latest version (v1.3.7).

**Comment by hellodrsoul** [comment]
I confirm the issue highlighted in my post above is now fixed in v 1.3.7. Obliged
