### ISSUE TITLE
增加跳转到书签页的功能

### ISSUE THREAD

**Issue by PaulHerrero** [qinxs/Ease-Bookmarks#13]
<img width="303" alt="Snipaste_2022-11-18_13-46-19" src="https://user-images.githubusercontent.com/56058332/202629961-0d4fe837-e2aa-4814-b7b4-e011411fe9bf.png">

希望可以在红框位置增加一键跳转到 edge://favorites/ 的按钮

**Comment by qinxs** [comment]
点扩展图标 右键 有打开书签管理器的菜单

`footer` 下面那个位置，如果其他书签栏里有书签 会显示`其他书签`

![1](https://user-images.githubusercontent.com/13647698/202747605-45af0b20-9ba0-4e80-9b87-5bebf6e13bdd.png)


以后UI有大调整 再考虑加在这个位置~

**Comment by qinxs** [comment]
> <img alt="Snipaste_2022-11-18_13-46-19" width="303" src="https://user-images.githubusercontent.com/56058332/202629961-0d4fe837-e2aa-4814-b7b4-e011411fe9bf.png">
> 
> 希望可以在红框位置增加一键跳转到 edge://favorites/ 的按钮

最新版（v1.3.9）已增加了此功能，你更新下~

**Comment by PaulHerrero** [comment]
> > <img alt="Snipaste_2022-11-18_13-46-19" width="303" src="https://user-images.githubusercontent.com/56058332/202629961-0d4fe837-e2aa-4814-b7b4-e011411fe9bf.png">
> > 希望可以在红框位置增加一键跳转到 edge://favorites/ 的按钮
> 
> 最新版（v1.3.9）已增加了此功能，你更新下~

感谢！
