### ISSUE TITLE
Issues using in Korean

### ISSUE THREAD

**Issue by JJay1** [qinxs/Ease-Bookmarks#16]
Please refer to the following link

https://imgur.com/a/LP9XMVU

1. Typing "영어" searches only for bookmarks containing "영". You have to hit the space key once to completely search for bookmarks with "영어". 
2. As you can see, there is a question mark in place of a symbol indicating folders parent-child relations.

Thank you for your hard work.

**Comment by qinxs** [comment]
Regarding your question:

1 I have repeatedly looked at the frames associated with the gif you provided and found the problem;
Before you enter "영어" but not the space, the "어" character is still in the synthesis stage, so the actual search character is still "영".
Note the difference between the search characters in Figure 1 and Figure 2 (the "영" character is underlined)
![001](https://user-images.githubusercontent.com/13647698/235583281-89a2a143-8fff-419b-9046-66f3f259a3b2.png)


2 This is how it is designed
  1) Open the subfolder from the parent directory list (the navigation bar symbol is ">")
  2) Open the folder from the list of search results (the navigation bar symbol is "?")

**Comment by JJay1** [comment]
[12.webm](https://user-images.githubusercontent.com/50947494/235623869-8eab2b26-e44a-4786-a199-6fd06c7eed2a.webm)

If you type "영어", as you said it is still recognized as a synthesis stage. Yeah, That's the problem. It should be recognized as a completed letter even if there is no adding space or right arrow key.

Here is another extension for an example. 

In this extension, typing "영" will return results containing "영". 
If you type "영어", you will get results that include "영어" (not "영") without pressing the space or right arrow key.

Whereas in Ease Bookmarks, hitting "영" doesn't produce anything. 
Typing "영어" will return results containing "영" (should be "영어"). This is not the right way for Korean users.
The results should include all characters at any time, even without pressing the space or right arrow keys. 
This is common thing with applications that have search features and google search has also fixed for the problem in the past.

The extension used as an example is open source. I don't know much about coding, but I hope it helps you to look into the problem.

https://github.com/jamesrr39/chrome-bookmark-search
https://chrome.google.com/webstore/detail/bookmark-search/fcjphnojgeikgjajhlihdjnljnbpfhmi

**Comment by qinxs** [comment]
Okay, I'll learn more about the search effect of various other language requirements.

Later versions of the unified modification or add relevant configuration items

**Comment by qinxs** [comment]
Hello, this issue has been handled, please update it to the latest version (v1.6.2).

**Comment by JJay1** [comment]
I appreciate your work. I can see the issue fixed. But unfortunately, there's a problem that didn't exist in the previous version: you have to press space key three times to make a space. Please see the attached video.

https://github.com/qinxs/Ease-Bookmarks/assets/50947494/61cccfad-62f4-472f-90de-40b6ed8833d6

**Comment by qinxs** [comment]
Sorry for the late reply.

Now you can set the hotkeyConfigTable in the
`chrome-extension://jnlhiobkddpipmgjkpkhiefaahibkeke/options.html#configTable` page, 
change the value of `hotkeyCancelSeleted`:
from Space to -Space.

However, the search does not support space characters.
