### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by earlytalk** [qinxs/Ease-Bookmarks#17]
首先谢谢qinxs推出该插件，也是我寻找多年比较满意好用的插件
我给一些建议：
1. 既然书签显示顺序是从上向下，那么鼠标滚轮的操作从左向右，是不是更好些呢
2. 书签的展示宽度能不能增大一些呢，或者不限制宽度，或者用户可以自定义宽度，或者用户可以用鼠标拉宽度呢
3. 当书签超过几百或者上千的时候，是否可以增加一个二级，三级........书签标示，当然，是可以覆盖一级书签显示的
另外请问chrome1.6.2和edge1.6.0版本性质是一致的么
谢谢你推出这么好的插件

**Comment by qinxs** [comment]
你好：
  1. 浏览器默认支持的是鼠标滚轮竖向滚动，横向滚动需要自己用js实现
  而且，书签条目的大小为280*28(宽高)，横向控制效果不好

  2. 由于浏览器本身的限制，popup窗口最大尺寸为800*600
  后续考虑开放设置布局为各列的宽度

  3. 没明白什么意思，截图详细说明一下~

不同版本是代码是不一样的。edge和chrome版本不一样，是因为审核时间不同
现在edge也通过审核了，版本都是1.6.2了

**Comment by earlytalk** [comment]
不知道你有没有用过360浏览器，我想说的就是类似360浏览器那样的书签展示

**Comment by akiyamamio2nd** [comment]
第2点比较影响使用，如果改善了就完美。

**Comment by qinxs** [comment]
@earlytalk @akiyamamio2nd 

现在支持通过内置参数去调整（1-N列）对应的宽度，最大800px
参数地址：chrome-extension://jnlhiobkddpipmgjkpkhiefaahibkeke/options.html#configTable
