### ISSUE TITLE
希望可以横向滚动

### ISSUE THREAD

**Issue by fzxj520** [qinxs/Ease-Bookmarks#18]
非常感谢  ！非常好  ！
希望可以横向滚动就完美了 （现在只能上下滚动）（ 就是 Quick书签菜单 的滚动布局 ）
每列条数就是控制菜单高度？？ 但是视乎无效

**Comment by qinxs** [comment]
@fzxj520 
你好 最新版（1.7.1）已经支持横向滚动

每列条数是控制菜单高度的
但书签数目超过了`每列条数`*`列数`后 就会打破这个限制
