### ISSUE TITLE
[FR] 希望可以取消 space 快捷键的取消选中功能, 或者设置成其他快捷键

### ISSUE THREAD

**Issue by doit132** [qinxs/Ease-Bookmarks#19]
这个 space 取消选中功能有什么具体的应用场所吗? 

# space 取消选中功能带来的不便

之所以想要取消这个功能, 是因为在搜索书签的时候, 不可避免的要输入多个关键字, 但是第一个关键字输入后, 想要输入空格, 此时按下空格并不会在输入框中增添空格, 而是取消书签的选中, 只有再次按下空格键的时候才会在输入框后面增添一个空格, 这有点反直觉

感谢作者开发出如此优秀的扩展

**Comment by qinxs** [comment]
新版本支持修改了

将内置参数中`hotkeyCancelSeleted`的值：
由`Space`改为`-Space`（也可以是其他的单个按键）

你可以通过 https://www.toptal.com/developers/keycode 获取单个按键（event.code）
