### ISSUE TITLE
CTRL修饰键-在后台打开页面

### ISSUE THREAD

**Issue by gbsix** [qinxs/Ease-Bookmarks#20]
Chrome默认按Ctrl+单击就是在后台打开书签，而在这个扩展里却变成了Ctrl当前页打开，shift才是后台打开，混乱了，很不习惯。希望操作习惯和Chrome保持一致。谢谢！

**Comment by qinxs** [comment]
设计之初 没注意这个问题 下个版本调整

**Comment by qinxs** [comment]
@gbsix 
最新版（v1.7.1）已更改，请更新一下~
