### ISSUE TITLE
希望可以增加书签移动到父目录的功能

### ISSUE THREAD

**Issue by lqzhappy** [qinxs/Ease-Bookmarks#21]
目前很容易通过拖放把书签从父目录移动到子目录，但是反过来操作却不行，希望增加一个移动到父目录的功能，不然每次还要切换到系统自带的书签管理器比较不方便

**Comment by qinxs** [comment]
移动到子目录是 书签拖拽排序 顺带的功能

移动到父目录的本质是 跨目录移动
这个功能 会增加维护成本和损失一些性能 所以暂时不增加了哈

书签跨目录移动 本来也是一个低频操作
建议操作时 使用书签管理页面 chrome://bookmarks/（快捷键`Ctrl + Shift + O`）
