### ISSUE TITLE
添加书签有点不方便，建议增加“添加到本文件夹”按钮功能

### ISSUE THREAD

**Issue by gengruihuan** [qinxs/Ease-Bookmarks#22]
模仿下360极速的就挺好的

**Comment by qinxs** [comment]
在360急速浏览器里，“添加到本文件夹”按钮挺和谐的

但在本扩展的界面设计里，添加这个按钮会很不协调
而且扩展的pop窗口的最大为600*800（360浏览器本身则没这个限制），添加这个按钮会占用宝贵的空间

另外 “添加到本文件夹”按钮只会把书签添加到文件夹末尾
而右键->新建书签->保存，则可以直接添加到合适的位置

综合考虑，本扩展不增加此按钮哈
