### ISSUE TITLE
建議啟動位置增加上次搜索關鍵字

### ISSUE THREAD

**Issue by windvane** [qinxs/Ease-Bookmarks#23]
建議啟動位置增加上次搜索關鍵字

**Comment by qinxs** [comment]
感觉这个意义不大吧

搜索到书签打开后 就是一个tab了 重启浏览器 应该使用Ctrl + Shift + T 恢复标签页（或者用Tab Session Manager扩展恢复）

如果是需要从搜索结果连续打开多个书签 点击书签时 按住Shift键（后续版本可能改为Ctrl键 参考#20）

**Comment by windvane** [comment]
有時搜索結果出來很多，但又不想一次打開多個書籤時就會用到。
我之前用的擴充功能就有此功能，所以想說是否有可能添加，謝謝！

**Comment by windvane** [comment]
謝謝傾聽需求並於1.7.2版增加此功能！😃

**Comment by qinxs** [comment]
> 謝謝傾聽需求並於1.7.2版增加此功能！😃

更新到最新版 (v1.7.2)
然后将内置参数 `keepLastSearchValue` 改为 `1`

修改页面 /options.html#configTable
