### ISSUE TITLE
某些js脚本无法使用

### ISSUE THREAD

**Issue by JJcdomat** [qinxs/Ease-Bookmarks#24]
javascript:navigator.clipboard.writeText(decodeURIComponent(window.location));
这个无法使用，用浏览器自带的就完全没问题。

**Comment by qinxs** [comment]
经测试
navigator.clipboard.writeText需要用户交互才能执行

所以不支持在chrome的API（此处是`chrome.tabs.executeScript`）里执行
暂时没有解决办法

**Comment by qinxs** [comment]
@JJcdomat 你好
最新版（v1.7.6）支持最外层使用navigator.clipboard.writeText了
如 javascript:XXX.(XXX...);

但XXX内部不能包含navigator.clipboard.writeText
