### ISSUE TITLE
如果能支持子文件夹的书签在新的一列展示就更好了

### ISSUE THREAD

**Issue by two867** [qinxs/Ease-Bookmarks#25]
就是这个插件, tidy bookmarks,  没有老哥的界面好看, 
https://chromewebstore.google.com/detail/tidy-bookmarks/bennikkpnelmfdiijpdclfincmnoabae
就像浏览器展示子文件夹那样, 每个子文件夹都是新的一列
可以参考一下

**Comment by qinxs** [comment]
由于扩展的前期设计问题 很难实现或者兼容这种界面了

而且 这种会跳来跳去 体验也不太好吧（由于扩展被限制 做不到浏览器原生那种效果）

**Comment by C107-9** [comment]
试了下，这个扩展用着也还不错
