### ISSUE TITLE
360X快速瀏覽器無法新建文件夾和書簽

### ISSUE THREAD

**Issue by hxhwing0522** [qinxs/Ease-Bookmarks#28]
您好。
問題1: 在360X快速瀏覽器上無法新建文件夾和書簽

問題2: 
如何打開中鍵新建書簽的功能。(已在設置里也改了fastCreate 2)
請問扩展控制台是在哪里打開的? 
我是在F12 > 控制台輸入 BM.set('fastCreate', 2) ，但是命令無效。
https://github.com/qinxs/Ease-Bookmarks/issues/15

首先謝謝作者的這個插件。
我目前在嘗試從360X換到EDGE上(因為360X最近經常崩潰)，但是EDGE的收藏夾邏輯真的用得想哭了 T^T。
(尤其用了這麼多年的360X收藏夾的方便)。
所以現在被迫又用回360X快速瀏覽器。
幸好找到作者這個插件(B站留言看到的，找了很多書簽插件)。
現在主要是先用用，看看能不能代替360的書簽習慣。謝謝

**Comment by qinxs** [comment]
### Q1：
这个360浏览器对扩展做了改动或限制导致的，官方没有任何文档说明，不能修复
比如创建书签代码：
```js
chrome.bookmarks.create({
  'parentId': '1',
  'index': 0,
  'title': 'Ease-Bookmarks',
  'url': 'https://github.com/qinxs/Ease-Bookmarks'
});
```

在360的书签管理器页面的控制台 能够创建书签，但在本扩展的控制台就报错了
> 作为对比 在chrome和edge里 本扩展都能正常创建书签和文件夹

### Q2：
chrome-extension://jnlhiobkddpipmgjkpkhiefaahibkeke/options.html#configTable
扩展的内置参数 直接在这个页面修改就可以了 不用去控制台执行
（由于Q1问题的存在 改了后 还是不能创建书签和文件夹）

最后 如果方便 建议去360社区反馈此兼容问题（并附带此 issue 链接）
感谢反馈~

**Comment by hxhwing0522** [comment]
### Q1: 既然是360的問題，那就沒辦法。


### Q2:  請問意思只需要在插件的内置参数修改嗎? (Chrome/Edge) 
```
0：默认值，不启用
2：启用，只对文件夹有效，书签添加到该文件夹中
```
 #### (EDGE如下) extension://addbgeibeffkokpabpbpmdpehfbegchl/options.html#configTable

![image](https://github.com/qinxs/Ease-Bookmarks/assets/35884432/e9cdb58b-567d-461d-ae77-7b547544ca55)

```
功能：中键点击书签favicon图标，快速把当前网址添加到书签（详见 https://github.com/qinxs/Ease-Bookmarks/issues/15）
```
![image](https://github.com/qinxs/Ease-Bookmarks/assets/35884432/eaac9b63-2fa9-49bf-a04d-15faabe18b29)


然後，只需要在EDGE里，CTRL+Q打開插件的收藏視窗，在里面按中鍵點擊一個文件夾圖標，就可以把書簽加到里面去嗎? 

因為我在EDGE里也改了配置參數-2，也是用不了中鍵添加書簽。所以好奇我是不是漏掉什麼步驟

**Comment by qinxs** [comment]
@hxhwing0522 操作和理解都没问题

但无论何种方式添加书签、文件夹 最终还是要调用`chrome.bookmarks.create`这个API
这又回到问题1了 所以添加不了

我试了 还包括编辑、删除都有问题 所以最好还是反馈给360社区

我电脑上测试了chrome、edge、chromium 扩展都没问题 所有功能正常 UI页比较一致
但第三方 360（还有Vivaldi）都有或多或少的兼容问题
其根本原因就是他们修改或限制了API 但官方没有文档 所以我也处理不了

**Comment by hxhwing0522** [comment]
> @hxhwing0522 操作和理解都没问题
> 
> 但无论何种方式添加书签、文件夹 最终还是要调用`chrome.bookmarks.create`这个API 这又回到问题1了 所以添加不了
> 
> 我试了 还包括编辑、删除都有问题 所以最好还是反馈给360社区
> 
> 我电脑上测试了chrome、edge、chromium 扩展都没问题 所有功能正常 UI页比较一致 但第三方 360（还有Vivaldi）都有或多或少的兼容问题 其根本原因就是他们修改或限制了API 但官方没有文档 所以我也处理不了

360X已經放棄了這個功能。
但我在EDGE和chrome上都測試過，都是無法使用。

**Comment by qinxs** [comment]
我这儿可以的 你看操作是不是一样的

![1](https://github.com/qinxs/Ease-Bookmarks/assets/13647698/e26ceb44-ab20-4094-bf62-bb2c40bb238d)

**Comment by hxhwing0522** [comment]
> 我这儿可以的 你看操作是不是一样的
> 
> ![1](https://private-user-images.githubusercontent.com/13647698/340074992-e26ceb44-ab20-4094-bf62-bb2c40bb238d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjYxMjksIm5iZiI6MTcxODUyNTgyOSwicGF0aCI6Ii8xMzY0NzY5OC8zNDAwNzQ5OTItZTI2Y2ViNDQtYWIyMC00MDk0LWJmNjItYmIyYzQwYmIyMzhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA4MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMGMxYWM5MjFmNjM2MTZmNzc0Y2JiY2M3OTQxMzYzNzUwMzEzYzQ3ZGE4ODNlMzA0MDA1NWE2YTI3NDQxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJU1QgNCNDXY4pZnr0M7poR_5mhR7yJPVBspPYjRWKA) [ ![1](https://private-user-images.githubusercontent.com/13647698/340074992-e26ceb44-ab20-4094-bf62-bb2c40bb238d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjYxMjksIm5iZiI6MTcxODUyNTgyOSwicGF0aCI6Ii8xMzY0NzY5OC8zNDAwNzQ5OTItZTI2Y2ViNDQtYWIyMC00MDk0LWJmNjItYmIyYzQwYmIyMzhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA4MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMGMxYWM5MjFmNjM2MTZmNzc0Y2JiY2M3OTQxMzYzNzUwMzEzYzQ3ZGE4ODNlMzA0MDA1NWE2YTI3NDQxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJU1QgNCNDXY4pZnr0M7poR_5mhR7yJPVBspPYjRWKA) ](https://private-user-images.githubusercontent.com/13647698/340074992-e26ceb44-ab20-4094-bf62-bb2c40bb238d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjYxMjksIm5iZiI6MTcxODUyNTgyOSwicGF0aCI6Ii8xMzY0NzY5OC8zNDAwNzQ5OTItZTI2Y2ViNDQtYWIyMC00MDk0LWJmNjItYmIyYzQwYmIyMzhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA4MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMGMxYWM5MjFmNjM2MTZmNzc0Y2JiY2M3OTQxMzYzNzUwMzEzYzQ3ZGE4ODNlMzA0MDA1NWE2YTI3NDQxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJU1QgNCNDXY4pZnr0M7poR_5mhR7yJPVBspPYjRWKA) [ ](https://private-user-images.githubusercontent.com/13647698/340074992-e26ceb44-ab20-4094-bf62-bb2c40bb238d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjYxMjksIm5iZiI6MTcxODUyNTgyOSwicGF0aCI6Ii8xMzY0NzY5OC8zNDAwNzQ5OTItZTI2Y2ViNDQtYWIyMC00MDk0LWJmNjItYmIyYzQwYmIyMzhkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA4MTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMGMxYWM5MjFmNjM2MTZmNzc0Y2JiY2M3OTQxMzYzNzUwMzEzYzQ3ZGE4ODNlMzA0MDA1NWE2YTI3NDQxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJU1QgNCNDXY4pZnr0M7poR_5mhR7yJPVBspPYjRWKA)

可以了，謝謝作者。
1. 打開插件的設置，進入在右上角的内置参数頁面
2. 把fastCreate的參數改成2
3. 回到網頁
4. 打開插件的收藏夾視窗，將鼠標移到文件夾圖標上，鼠標會變成十字型移動圖標
5. 按中鍵，即可收藏頁面
