### ISSUE TITLE
对收藏夹的文件夹和书签进行排列

### ISSUE THREAD

**Issue by PiscesDreamer** [qinxs/Ease-Bookmarks#29]
很好用的扩展,但是缺少了对收藏夹文件夹和书签进行排列的功能,如果添加了这样的功能,
这个扩展会更强悍

**Comment by qinxs** [comment]
你好 扩展是支持文件夹内拖动排序的
鼠标放在书签、文件夹图标上  左键按住拖动进行排序

跨文件夹拖动排序 目前是不支持的
建议去浏览器本身的书签管理器页面（快捷键：`Ctrl + Shift + O`）操作

**Comment by PiscesDreamer** [comment]
> 你好 扩展是支持文件夹内拖动排序的 鼠标放在书签、文件夹图标上 左键按住拖动进行排序
> 
> 跨文件夹拖动排序 目前是不支持的 建议去浏览器本身的书签管理器页面（快捷键：`Ctrl + Shift + O`）操作

你好,我没法实现左键按住拖动排序, 这是我才来反馈的原因.
请问是什么原因造成了我无法拖动排序

**Comment by qinxs** [comment]
鼠标要放在 **图标** 上

![拖动排序](https://github.com/qinxs/Ease-Bookmarks/assets/13647698/2bef24d1-3d27-46ee-a580-49a2dbb32f21)

**Comment by PiscesDreamer** [comment]
> 鼠标要放在 **图标** 上
> 
> ![拖动排序](https://private-user-images.githubusercontent.com/13647698/341755109-2bef24d1-3d27-46ee-a580-49a2dbb32f21.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzE4MjcsIm5iZiI6MTcxODk3MTUyNywicGF0aCI6Ii8xMzY0NzY5OC8zNDE3NTUxMDktMmJlZjI0ZDEtM2QyNy00NmVlLWE1ODAtNDlhMmRiYjMyZjIxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEyMDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Nzc2MTA5ZDU3Nzc3M2VlNTk5ZTNkN2M4ZWNjYjBmNmJiNDEyYzgzOTk0YjQ5YjkzYmRiY2VjZjA2YjI0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k6FnyvAY_SL8yFVjUPoe84tYAxQcQMlAjcDjWCtA-mY) [ ![拖动排序](https://private-user-images.githubusercontent.com/13647698/341755109-2bef24d1-3d27-46ee-a580-49a2dbb32f21.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzE4MjcsIm5iZiI6MTcxODk3MTUyNywicGF0aCI6Ii8xMzY0NzY5OC8zNDE3NTUxMDktMmJlZjI0ZDEtM2QyNy00NmVlLWE1ODAtNDlhMmRiYjMyZjIxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEyMDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Nzc2MTA5ZDU3Nzc3M2VlNTk5ZTNkN2M4ZWNjYjBmNmJiNDEyYzgzOTk0YjQ5YjkzYmRiY2VjZjA2YjI0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k6FnyvAY_SL8yFVjUPoe84tYAxQcQMlAjcDjWCtA-mY) ](https://private-user-images.githubusercontent.com/13647698/341755109-2bef24d1-3d27-46ee-a580-49a2dbb32f21.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzE4MjcsIm5iZiI6MTcxODk3MTUyNywicGF0aCI6Ii8xMzY0NzY5OC8zNDE3NTUxMDktMmJlZjI0ZDEtM2QyNy00NmVlLWE1ODAtNDlhMmRiYjMyZjIxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEyMDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Nzc2MTA5ZDU3Nzc3M2VlNTk5ZTNkN2M4ZWNjYjBmNmJiNDEyYzgzOTk0YjQ5YjkzYmRiY2VjZjA2YjI0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k6FnyvAY_SL8yFVjUPoe84tYAxQcQMlAjcDjWCtA-mY) [ ](https://private-user-images.githubusercontent.com/13647698/341755109-2bef24d1-3d27-46ee-a580-49a2dbb32f21.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzE4MjcsIm5iZiI6MTcxODk3MTUyNywicGF0aCI6Ii8xMzY0NzY5OC8zNDE3NTUxMDktMmJlZjI0ZDEtM2QyNy00NmVlLWE1ODAtNDlhMmRiYjMyZjIxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDEyMDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Nzc2MTA5ZDU3Nzc3M2VlNTk5ZTNkN2M4ZWNjYjBmNmJiNDEyYzgzOTk0YjQ5YjkzYmRiY2VjZjA2YjI0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k6FnyvAY_SL8yFVjUPoe84tYAxQcQMlAjcDjWCtA-mY)

了解了,当外面的目录能排成三列的时候,点进其中一个目录,目录里面的书签只能排出一列或者两列的时候,管理窗口会自适应
的缩小宽度.  
能否提供个选项, 当选择排列为2或3列的时候阻止这种自适应伸缩. 让管理窗口固定成两列和三列的宽度.

**Comment by qinxs** [comment]
chrome-extension://jnlhiobkddpipmgjkpkhiefaahibkeke/options.html#configTable

参数 keepMaxCols 改为 1

**Comment by PiscesDreamer** [comment]
> chrome-extension://jnlhiobkddpipmgjkpkhiefaahibkeke/options.html#configTable
> 
> 参数 keepMaxCols 改为 1
可以了!感谢指导
