### ISSUE TITLE
不能在linux里安装的问题

### ISSUE THREAD

**Issue by BoltLi** [qinxs/Ease-Bookmarks#3]
我在edge和chrome中都试了，都不行，报错 invald manifest，后来用源码解压缩来安装，显示的问题才比较明显，就是没有设置linux的默认快捷键导致的安装失败，我手动加上了，就可以安装了，希望作者能够更新一下包，重新上传到edge和chrome 的应用商店，免去linux不能安装的麻烦。
在manifest.json里加对于linux的快捷键代码如下
```json
    "_execute_browser_action": {
      "suggested_key": {
        "windows": "Ctrl+Q",
        "mac": "Command+Q",
        "linux": "Ctrl+Q"  
      },
      "description": "打开/关闭扩展"
    }
```

**Comment by qinxs** [comment]
好的
感谢反馈~
