### ISSUE TITLE
请教下vivaldi如何安装该扩展

### ISSUE THREAD

**Issue by lee911214** [qinxs/Ease-Bookmarks#30]
如题，之前看过支持vivaldi，可是我下载的crx不能加载，压缩包解压后也不行，所以特来请教，感谢大佬开发这软件

**Comment by qinxs** [comment]
win10 Vivaldi.6.8.3381.46.x64 上 
打开扩展程序页的开发模式 crx就可以正常安装

但 Vivaldi 对书签API有更改 所以书签删除时 popup窗口里不会立即更新
