### ISSUE TITLE
标签搜索小问题反馈

### ISSUE THREAD

**Issue by Parantric** [qinxs/Ease-Bookmarks#33]
比如设置百度搜索网址的书签名称为：1111 搜索 百度 baidu，那么，通过快捷键 ctrl + Q 换出书签搜索栏并输入：1111，是可以显示出这个百度网站的书签的，如果输入：1111百度，也是可以的，输入：1111baidu的时候，首先输入1111是可以看到百度书签的，但是再输入英文或者字母，发现那个百度书签查不到的。也就是说如果输入的文本为：数字+字母，则这个由数字+字母组成的 input value，不能匹配到书签名中「包含」这个 input value 的书签。不知道是bug，还是这种情况本身就存在问题。

**Comment by qinxs** [comment]
搜索 使用的是chrome API `chrome.bookmarks.search`
我这儿测试结果跟 chrome://bookmarks/ 页面的搜索结果是一致的

不过 先输入1111 再输入中文百度 输入法合成有些问题 新版1.7.7已经修复 
感谢反馈

**Comment by Parantric** [comment]
好的，辛苦大佬，好像 GitHub 资源包那里还是 1.7.6，我看到更新日志是 1.7.7 了。😂

**Comment by Parantric** [comment]
> 搜索 使用的是 chrome API `chrome.bookmarks.search` 我这儿测试结果跟 chrome://bookmarks/ 页面的搜索结果是一致的
> 
> 不过 先输入 1111 再输入中文百度 输入法合成有些问题 新版 1.7.7 已经修复 感谢反馈

好的，辛苦大佬，好像 GitHub 资源包那里还是 1.7.6，我看到更新日志是 1.7.7 了。😂
