### ISSUE TITLE
Wishes: Customize columns

### ISSUE THREAD

**Issue by MadsJ-max** [qinxs/Ease-Bookmarks#5]
I have three wishes for the Ease Bookmark-plugin for Edge:

1. More bookmarks than 16 in a column
2. More width in a column
3. Less vertical spacing (padding) of bookmarks 

Is that possible with the Custom style?

Thanks in advance :-)

**Comment by qinxs** [comment]
hello,

for your question:
  1. this will be revised in the next version
  2. It is not easy to handle temporarily (because everyone's requirements may be different), and custom widths may be allowed in the future
  3. You can use  the custom style, like this:
   ```
:root {
  --height-item: 26px;
}
```

**Comment by MadsJ-max** [comment]
Thanks a lot for your quick answer.

4. Can the whole window be bigger (height and width)?

**Comment by qinxs** [comment]
The maximum size can only be 600*800, which is the limit of google
