### ISSUE TITLE
捉虫

### ISSUE THREAD

**Issue by MinatoAquaOfficial** [qinxs/Ease-Bookmarks#6]
超级好的插件，不过有2个小bug：

1.书签条目太多时，往底部滚动到最后一部分时会卡顿。设置为一栏会有此现象，设置多栏也有此现象。（类似现象在某个chrome插件也遇到过）
2.对倒数第二条目右键，扩展菜单会超出显示范围。对倒数第一条目右键则扩展菜单会**正常地**自适应向上打开。

**Comment by qinxs** [comment]
你好：
我用300+书签测试 没发现卡顿问题

能否提供下配置截图和书签导到文件（html格式的）?

**Comment by MinatoAquaOfficial** [comment]
> 
您好：
看到您回复，我马上反应过来是我浏览器缩放的问题。
因为屏幕是2k分辨率，所以浏览器设置了150%页面缩放，改为100%缩放后果然2个问题都得到解决。

**Comment by qinxs** [comment]
好的，那我关闭这条issue了~
