### ISSUE TITLE
书签拖动添加

### ISSUE THREAD

**Issue by xiaobaiweinuli** [qinxs/Ease-Bookmarks#7]
不能直接把书签拖动到文件夹中，不能改变文件夹中书签的位置（改变所在的文件夹-有A到B）

**Comment by qinxs** [comment]
以扩展的目前设计 很难实现跨文件件移动

看下常见问题[为何没有 复制/粘贴 功能？](https://github.com/qinxs/Ease-Bookmarks/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%EF%BC%88FAQ%EF%BC%89#%E4%B8%BA%E4%BD%95%E6%B2%A1%E6%9C%89-%E5%A4%8D%E5%88%B6%E7%B2%98%E8%B4%B4-%E5%8A%9F%E8%83%BD)
