### ISSUE TITLE
愿望清单：多列布局方式

### ISSUE THREAD

**Issue by icerayer** [qinxs/Ease-Bookmarks#8]
### 由于书签太多，目前插件显示的窗口还是太小，需要滚动多次才能看完，于是有了一点想法，不知可行性如何

- 展开书签文件夹时（包括初始书签栏）计算所有行总高度；
- 对比可见区域高度，如果<=可见区域高度的95%则窗口为单列，高度为行总高度，列宽度250px左右；
- 否则高度为可见区域高度的95%，拆出第二列，宽度加大一列，分配后若还有未分配则再加一列，直到分配完所有标签；
- 如果计算发现窗口总宽度>可见区域宽度，则表明窗口装不下，添加`滚动条`或`分页`。

这样可见区域的书签顺序符合添加的顺序

**Comment by icerayer** [comment]
### 补充
最后一条：添加`滚动条`或`分页`

**Comment by alem0n** [comment]
不好，这样丢失了书签作为插件的小巧性

**Comment by alem0n** [comment]
> 测试了下不行，768x568就出滚动条，
> 
> * Bookmark Sidebar好像是用iframe添加上的大窗口，
> * 是否可以单独开一个页面用来大窗口显示书签，用`chrome-extension://xxxx.html?xxx`这样的页面打开

这样做丢失了插件的小巧性，不是一个好提议

**Comment by yexiaoziSAS** [comment]
能不能增加个使用说明，比如修改标签页高度的代码是main {  min-height: 115px;}。

**Comment by qinxs** [comment]
> 能不能增加个使用说明，比如修改标签页高度的代码是main { min-height: 115px;}。

好的 后面会完善相关文档
